GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YmNiNmMxMmFmZjdjMGViZmFjNWVkZSIsImlhdCI6MTcyMzY2ODgwOSwiZXhwIjoxNzIzNjcyNDA5fQ.Lgh78DVuCspSGxvnLs5ldm8IF4XlDZ-Z7tk0KO8S4uA

{
  "title": "LAST NOTE",
  "author": "kostas",
  "url": "https://www.xyz.com",
  "likes": 32
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "You didn't find this, it found you",
  "author": "kostasP",
  "url": "https://www.idk.com",
  "likes": 128
}

###
DELETE http://localhost:3003/api/blogs/66bd19f1bad132252a0f3be2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YmNiNmMxMmFmZjdjMGViZmFjNWVkZSIsImlhdCI6MTcyMzY2OTIxMSwiZXhwIjoxNzIzNjcyODExfQ._v3Oq_0AQZSB8ULPZOS8FNhpSoBnSP-Ace1rfLVJVro